package org.jbpm.test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Person implements java.io.Serializable {

    static final long serialVersionUID = 1L;
    
    private String name;
    private String address;
    private int age;
    private boolean registered;

    public Person() {
    }

    public void setName(String name) {
        this.name = name;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    
    public void setAge(int age) {
        this.age = age;
    }
    
    public void setRegistered(boolean registered) {
        this.registered = registered;
    }
    
    public String getName() {
        return this.name;
    }
    
    public String getAddress() {
        return this.address;
    }
    
    public int getAge() {
        return this.age;
    }
    
    public boolean isRegistered() {
        return this.registered;
    }
    
    public String toString() {
        return "Person {Name="+name+", addess=" + address+", age="+age+",registered="+registered+"}";
    }
}